# Generated by Django 5.0.2 on 2024-03-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='product',
            new_name='service',
        ),
    ]
