# Generated by Django 5.0.2 on 2024-02-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0005_service_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
